#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Testik1.Resource", IsApplication=true)]

namespace Testik1
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Attribute.alpha = global::Testik1.Resource.Attribute.alpha;
			global::Xamarin.Essentials.Resource.Attribute.font = global::Testik1.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::Testik1.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::Testik1.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::Testik1.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::Testik1.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::Testik1.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::Testik1.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::Testik1.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontVariationSettings = global::Testik1.Resource.Attribute.fontVariationSettings;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::Testik1.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Attribute.ttcIndex = global::Testik1.Resource.Attribute.ttcIndex;
			global::Xamarin.Essentials.Resource.Color.androidx_core_ripple_material_light = global::Testik1.Resource.Color.androidx_core_ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.androidx_core_secondary_text_default_material_light = global::Testik1.Resource.Color.androidx_core_secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Color.browser_actions_bg_grey = global::Testik1.Resource.Color.browser_actions_bg_grey;
			global::Xamarin.Essentials.Resource.Color.browser_actions_divider_color = global::Testik1.Resource.Color.browser_actions_divider_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_text_color = global::Testik1.Resource.Color.browser_actions_text_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_title_color = global::Testik1.Resource.Color.browser_actions_title_color;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::Testik1.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::Testik1.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_max_width = global::Testik1.Resource.Dimension.browser_actions_context_menu_max_width;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_min_padding = global::Testik1.Resource.Dimension.browser_actions_context_menu_min_padding;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::Testik1.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::Testik1.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::Testik1.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::Testik1.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::Testik1.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_height = global::Testik1.Resource.Dimension.compat_notification_large_icon_max_height;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_width = global::Testik1.Resource.Dimension.compat_notification_large_icon_max_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::Testik1.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::Testik1.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::Testik1.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::Testik1.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::Testik1.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::Testik1.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::Testik1.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::Testik1.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::Testik1.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::Testik1.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::Testik1.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::Testik1.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::Testik1.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::Testik1.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::Testik1.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::Testik1.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::Testik1.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::Testik1.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::Testik1.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::Testik1.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::Testik1.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::Testik1.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::Testik1.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::Testik1.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::Testik1.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::Testik1.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::Testik1.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.accessibility_action_clickable_span = global::Testik1.Resource.Id.accessibility_action_clickable_span;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_0 = global::Testik1.Resource.Id.accessibility_custom_action_0;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_1 = global::Testik1.Resource.Id.accessibility_custom_action_1;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_10 = global::Testik1.Resource.Id.accessibility_custom_action_10;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_11 = global::Testik1.Resource.Id.accessibility_custom_action_11;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_12 = global::Testik1.Resource.Id.accessibility_custom_action_12;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_13 = global::Testik1.Resource.Id.accessibility_custom_action_13;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_14 = global::Testik1.Resource.Id.accessibility_custom_action_14;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_15 = global::Testik1.Resource.Id.accessibility_custom_action_15;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_16 = global::Testik1.Resource.Id.accessibility_custom_action_16;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_17 = global::Testik1.Resource.Id.accessibility_custom_action_17;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_18 = global::Testik1.Resource.Id.accessibility_custom_action_18;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_19 = global::Testik1.Resource.Id.accessibility_custom_action_19;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_2 = global::Testik1.Resource.Id.accessibility_custom_action_2;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_20 = global::Testik1.Resource.Id.accessibility_custom_action_20;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_21 = global::Testik1.Resource.Id.accessibility_custom_action_21;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_22 = global::Testik1.Resource.Id.accessibility_custom_action_22;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_23 = global::Testik1.Resource.Id.accessibility_custom_action_23;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_24 = global::Testik1.Resource.Id.accessibility_custom_action_24;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_25 = global::Testik1.Resource.Id.accessibility_custom_action_25;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_26 = global::Testik1.Resource.Id.accessibility_custom_action_26;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_27 = global::Testik1.Resource.Id.accessibility_custom_action_27;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_28 = global::Testik1.Resource.Id.accessibility_custom_action_28;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_29 = global::Testik1.Resource.Id.accessibility_custom_action_29;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_3 = global::Testik1.Resource.Id.accessibility_custom_action_3;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_30 = global::Testik1.Resource.Id.accessibility_custom_action_30;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_31 = global::Testik1.Resource.Id.accessibility_custom_action_31;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_4 = global::Testik1.Resource.Id.accessibility_custom_action_4;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_5 = global::Testik1.Resource.Id.accessibility_custom_action_5;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_6 = global::Testik1.Resource.Id.accessibility_custom_action_6;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_7 = global::Testik1.Resource.Id.accessibility_custom_action_7;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_8 = global::Testik1.Resource.Id.accessibility_custom_action_8;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_9 = global::Testik1.Resource.Id.accessibility_custom_action_9;
			global::Xamarin.Essentials.Resource.Id.actions = global::Testik1.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.action_container = global::Testik1.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::Testik1.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::Testik1.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::Testik1.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.async = global::Testik1.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::Testik1.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.browser_actions_header_text = global::Testik1.Resource.Id.browser_actions_header_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_items = global::Testik1.Resource.Id.browser_actions_menu_items;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_icon = global::Testik1.Resource.Id.browser_actions_menu_item_icon;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_text = global::Testik1.Resource.Id.browser_actions_menu_item_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_view = global::Testik1.Resource.Id.browser_actions_menu_view;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::Testik1.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.dialog_button = global::Testik1.Resource.Id.dialog_button;
			global::Xamarin.Essentials.Resource.Id.forever = global::Testik1.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::Testik1.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::Testik1.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::Testik1.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::Testik1.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.line1 = global::Testik1.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::Testik1.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.normal = global::Testik1.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::Testik1.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::Testik1.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::Testik1.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::Testik1.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::Testik1.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_actions = global::Testik1.Resource.Id.tag_accessibility_actions;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_clickable_spans = global::Testik1.Resource.Id.tag_accessibility_clickable_spans;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_heading = global::Testik1.Resource.Id.tag_accessibility_heading;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_pane_title = global::Testik1.Resource.Id.tag_accessibility_pane_title;
			global::Xamarin.Essentials.Resource.Id.tag_screen_reader_focusable = global::Testik1.Resource.Id.tag_screen_reader_focusable;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::Testik1.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_event_manager = global::Testik1.Resource.Id.tag_unhandled_key_event_manager;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_listeners = global::Testik1.Resource.Id.tag_unhandled_key_listeners;
			global::Xamarin.Essentials.Resource.Id.text = global::Testik1.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::Testik1.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::Testik1.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::Testik1.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::Testik1.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_page = global::Testik1.Resource.Layout.browser_actions_context_menu_page;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_row = global::Testik1.Resource.Layout.browser_actions_context_menu_row;
			global::Xamarin.Essentials.Resource.Layout.custom_dialog = global::Testik1.Resource.Layout.custom_dialog;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::Testik1.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::Testik1.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::Testik1.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::Testik1.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::Testik1.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::Testik1.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.copy_toast_msg = global::Testik1.Resource.String.copy_toast_msg;
			global::Xamarin.Essentials.Resource.String.fallback_menu_item_copy_link = global::Testik1.Resource.String.fallback_menu_item_copy_link;
			global::Xamarin.Essentials.Resource.String.fallback_menu_item_open_in_browser = global::Testik1.Resource.String.fallback_menu_item_open_in_browser;
			global::Xamarin.Essentials.Resource.String.fallback_menu_item_share_link = global::Testik1.Resource.String.fallback_menu_item_share_link;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::Testik1.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::Testik1.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::Testik1.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::Testik1.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::Testik1.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::Testik1.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::Testik1.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::Testik1.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem = global::Testik1.Resource.Styleable.ColorStateListItem;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_alpha = global::Testik1.Resource.Styleable.ColorStateListItem_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_alpha = global::Testik1.Resource.Styleable.ColorStateListItem_android_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_color = global::Testik1.Resource.Styleable.ColorStateListItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::Testik1.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::Testik1.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::Testik1.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::Testik1.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::Testik1.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::Testik1.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::Testik1.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::Testik1.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::Testik1.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::Testik1.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::Testik1.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_ttcIndex = global::Testik1.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::Testik1.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::Testik1.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::Testik1.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::Testik1.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::Testik1.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::Testik1.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor = global::Testik1.Resource.Styleable.GradientColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem = global::Testik1.Resource.Styleable.GradientColorItem;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_color = global::Testik1.Resource.Styleable.GradientColorItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_offset = global::Testik1.Resource.Styleable.GradientColorItem_android_offset;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerColor = global::Testik1.Resource.Styleable.GradientColor_android_centerColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerX = global::Testik1.Resource.Styleable.GradientColor_android_centerX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerY = global::Testik1.Resource.Styleable.GradientColor_android_centerY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endColor = global::Testik1.Resource.Styleable.GradientColor_android_endColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endX = global::Testik1.Resource.Styleable.GradientColor_android_endX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endY = global::Testik1.Resource.Styleable.GradientColor_android_endY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_gradientRadius = global::Testik1.Resource.Styleable.GradientColor_android_gradientRadius;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startColor = global::Testik1.Resource.Styleable.GradientColor_android_startColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startX = global::Testik1.Resource.Styleable.GradientColor_android_startX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startY = global::Testik1.Resource.Styleable.GradientColor_android_startY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_tileMode = global::Testik1.Resource.Styleable.GradientColor_android_tileMode;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_type = global::Testik1.Resource.Styleable.GradientColor_android_type;
			global::Xamarin.Essentials.Resource.Xml.image_share_filepaths = global::Testik1.Resource.Xml.image_share_filepaths;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::Testik1.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int abc_fade_in = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int abc_fade_out = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int abc_grow_fade_in_from_bottom = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int abc_popup_enter = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int abc_popup_exit = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int abc_shrink_fade_out_from_bottom = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int abc_slide_in_bottom = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int abc_slide_in_top = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int abc_slide_out_bottom = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int abc_slide_out_top = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int abc_tooltip_enter = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int abc_tooltip_exit = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int btn_checkbox_to_checked_box_inner_merged_animation = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int btn_checkbox_to_checked_box_outer_merged_animation = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int btn_checkbox_to_checked_icon_null_animation = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int btn_checkbox_to_unchecked_box_inner_merged_animation = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int btn_checkbox_to_unchecked_check_path_merged_animation = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int btn_checkbox_to_unchecked_icon_null_animation = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int btn_radio_to_off_mtrl_dot_group_animation = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int btn_radio_to_off_mtrl_ring_outer_animation = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int btn_radio_to_off_mtrl_ring_outer_path_animation = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int btn_radio_to_on_mtrl_dot_group_animation = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int btn_radio_to_on_mtrl_ring_outer_animation = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int btn_radio_to_on_mtrl_ring_outer_path_animation = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int design_bottom_sheet_slide_in = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int design_bottom_sheet_slide_out = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int design_snackbar_in = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int design_snackbar_out = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int fragment_close_enter = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int fragment_close_exit = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int fragment_fade_enter = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int fragment_fade_exit = 2130771999;
			
			// aapt resource value: 0x7F010020
			public const int fragment_fast_out_extra_slow_in = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int fragment_open_enter = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int fragment_open_exit = 2130772002;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public const int design_appbar_state_list_animator = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int design_fab_hide_motion_spec = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int design_fab_show_motion_spec = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int mtrl_btn_state_list_anim = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int mtrl_btn_unelevated_state_list_anim = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int mtrl_chip_state_list_anim = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int mtrl_fab_hide_motion_spec = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int mtrl_fab_show_motion_spec = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int mtrl_fab_transformation_sheet_collapse_spec = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int mtrl_fab_transformation_sheet_expand_spec = 2130837513;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F030000
			public const int actionBarDivider = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int actionBarItemBackground = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int actionBarPopupTheme = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int actionBarSize = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int actionBarSplitStyle = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int actionBarStyle = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int actionBarTabBarStyle = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int actionBarTabStyle = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int actionBarTabTextStyle = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int actionBarTheme = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int actionBarWidgetTheme = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int actionButtonStyle = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int actionDropDownStyle = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int actionLayout = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int actionMenuTextAppearance = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int actionMenuTextColor = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int actionModeBackground = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int actionModeCloseButtonStyle = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int actionModeCloseDrawable = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int actionModeCopyDrawable = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int actionModeCutDrawable = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int actionModeFindDrawable = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int actionModePasteDrawable = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int actionModePopupWindowStyle = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int actionModeSelectAllDrawable = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int actionModeShareDrawable = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int actionModeSplitBackground = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int actionModeStyle = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int actionModeWebSearchDrawable = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int actionOverflowButtonStyle = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int actionOverflowMenuStyle = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int actionProviderClass = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int actionViewClass = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int activityChooserViewStyle = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int alertDialogButtonGroupStyle = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int alertDialogCenterButtons = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int alertDialogStyle = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int alertDialogTheme = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int allowStacking = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int alpha = 2130903079;
			
			// aapt resource value: 0x7F030028
			public const int alphabeticModifiers = 2130903080;
			
			// aapt resource value: 0x7F030029
			public const int arrowHeadLength = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int arrowShaftLength = 2130903082;
			
			// aapt resource value: 0x7F03002B
			public const int autoCompleteTextViewStyle = 2130903083;
			
			// aapt resource value: 0x7F03002C
			public const int autoSizeMaxTextSize = 2130903084;
			
			// aapt resource value: 0x7F03002D
			public const int autoSizeMinTextSize = 2130903085;
			
			// aapt resource value: 0x7F03002E
			public const int autoSizePresetSizes = 2130903086;
			
			// aapt resource value: 0x7F03002F
			public const int autoSizeStepGranularity = 2130903087;
			
			// aapt resource value: 0x7F030030
			public const int autoSizeTextType = 2130903088;
			
			// aapt resource value: 0x7F030031
			public const int background = 2130903089;
			
			// aapt resource value: 0x7F030032
			public const int backgroundSplit = 2130903090;
			
			// aapt resource value: 0x7F030033
			public const int backgroundStacked = 2130903091;
			
			// aapt resource value: 0x7F030034
			public const int backgroundTint = 2130903092;
			
			// aapt resource value: 0x7F030035
			public const int backgroundTintMode = 2130903093;
			
			// aapt resource value: 0x7F030036
			public const int barLength = 2130903094;
			
			// aapt resource value: 0x7F030037
			public const int behavior_autoHide = 2130903095;
			
			// aapt resource value: 0x7F030038
			public const int behavior_fitToContents = 2130903096;
			
			// aapt resource value: 0x7F030039
			public const int behavior_hideable = 2130903097;
			
			// aapt resource value: 0x7F03003A
			public const int behavior_overlapTop = 2130903098;
			
			// aapt resource value: 0x7F03003B
			public const int behavior_peekHeight = 2130903099;
			
			// aapt resource value: 0x7F03003C
			public const int behavior_skipCollapsed = 2130903100;
			
			// aapt resource value: 0x7F03003E
			public const int borderlessButtonStyle = 2130903102;
			
			// aapt resource value: 0x7F03003D
			public const int borderWidth = 2130903101;
			
			// aapt resource value: 0x7F03003F
			public const int bottomAppBarStyle = 2130903103;
			
			// aapt resource value: 0x7F030040
			public const int bottomNavigationStyle = 2130903104;
			
			// aapt resource value: 0x7F030041
			public const int bottomSheetDialogTheme = 2130903105;
			
			// aapt resource value: 0x7F030042
			public const int bottomSheetStyle = 2130903106;
			
			// aapt resource value: 0x7F030043
			public const int boxBackgroundColor = 2130903107;
			
			// aapt resource value: 0x7F030044
			public const int boxBackgroundMode = 2130903108;
			
			// aapt resource value: 0x7F030045
			public const int boxCollapsedPaddingTop = 2130903109;
			
			// aapt resource value: 0x7F030046
			public const int boxCornerRadiusBottomEnd = 2130903110;
			
			// aapt resource value: 0x7F030047
			public const int boxCornerRadiusBottomStart = 2130903111;
			
			// aapt resource value: 0x7F030048
			public const int boxCornerRadiusTopEnd = 2130903112;
			
			// aapt resource value: 0x7F030049
			public const int boxCornerRadiusTopStart = 2130903113;
			
			// aapt resource value: 0x7F03004A
			public const int boxStrokeColor = 2130903114;
			
			// aapt resource value: 0x7F03004B
			public const int boxStrokeWidth = 2130903115;
			
			// aapt resource value: 0x7F03004C
			public const int buttonBarButtonStyle = 2130903116;
			
			// aapt resource value: 0x7F03004D
			public const int buttonBarNegativeButtonStyle = 2130903117;
			
			// aapt resource value: 0x7F03004E
			public const int buttonBarNeutralButtonStyle = 2130903118;
			
			// aapt resource value: 0x7F03004F
			public const int buttonBarPositiveButtonStyle = 2130903119;
			
			// aapt resource value: 0x7F030050
			public const int buttonBarStyle = 2130903120;
			
			// aapt resource value: 0x7F030051
			public const int buttonCompat = 2130903121;
			
			// aapt resource value: 0x7F030052
			public const int buttonGravity = 2130903122;
			
			// aapt resource value: 0x7F030053
			public const int buttonIconDimen = 2130903123;
			
			// aapt resource value: 0x7F030054
			public const int buttonPanelSideLayout = 2130903124;
			
			// aapt resource value: 0x7F030055
			public const int buttonStyle = 2130903125;
			
			// aapt resource value: 0x7F030056
			public const int buttonStyleSmall = 2130903126;
			
			// aapt resource value: 0x7F030057
			public const int buttonTint = 2130903127;
			
			// aapt resource value: 0x7F030058
			public const int buttonTintMode = 2130903128;
			
			// aapt resource value: 0x7F030059
			public const int cardBackgroundColor = 2130903129;
			
			// aapt resource value: 0x7F03005A
			public const int cardCornerRadius = 2130903130;
			
			// aapt resource value: 0x7F03005B
			public const int cardElevation = 2130903131;
			
			// aapt resource value: 0x7F03005C
			public const int cardMaxElevation = 2130903132;
			
			// aapt resource value: 0x7F03005D
			public const int cardPreventCornerOverlap = 2130903133;
			
			// aapt resource value: 0x7F03005E
			public const int cardUseCompatPadding = 2130903134;
			
			// aapt resource value: 0x7F03005F
			public const int cardViewStyle = 2130903135;
			
			// aapt resource value: 0x7F030060
			public const int checkboxStyle = 2130903136;
			
			// aapt resource value: 0x7F030061
			public const int checkedChip = 2130903137;
			
			// aapt resource value: 0x7F030062
			public const int checkedIcon = 2130903138;
			
			// aapt resource value: 0x7F030063
			public const int checkedIconEnabled = 2130903139;
			
			// aapt resource value: 0x7F030064
			public const int checkedIconVisible = 2130903140;
			
			// aapt resource value: 0x7F030065
			public const int checkedTextViewStyle = 2130903141;
			
			// aapt resource value: 0x7F030066
			public const int chipBackgroundColor = 2130903142;
			
			// aapt resource value: 0x7F030067
			public const int chipCornerRadius = 2130903143;
			
			// aapt resource value: 0x7F030068
			public const int chipEndPadding = 2130903144;
			
			// aapt resource value: 0x7F030069
			public const int chipGroupStyle = 2130903145;
			
			// aapt resource value: 0x7F03006A
			public const int chipIcon = 2130903146;
			
			// aapt resource value: 0x7F03006B
			public const int chipIconEnabled = 2130903147;
			
			// aapt resource value: 0x7F03006C
			public const int chipIconSize = 2130903148;
			
			// aapt resource value: 0x7F03006D
			public const int chipIconTint = 2130903149;
			
			// aapt resource value: 0x7F03006E
			public const int chipIconVisible = 2130903150;
			
			// aapt resource value: 0x7F03006F
			public const int chipMinHeight = 2130903151;
			
			// aapt resource value: 0x7F030070
			public const int chipSpacing = 2130903152;
			
			// aapt resource value: 0x7F030071
			public const int chipSpacingHorizontal = 2130903153;
			
			// aapt resource value: 0x7F030072
			public const int chipSpacingVertical = 2130903154;
			
			// aapt resource value: 0x7F030073
			public const int chipStandaloneStyle = 2130903155;
			
			// aapt resource value: 0x7F030074
			public const int chipStartPadding = 2130903156;
			
			// aapt resource value: 0x7F030075
			public const int chipStrokeColor = 2130903157;
			
			// aapt resource value: 0x7F030076
			public const int chipStrokeWidth = 2130903158;
			
			// aapt resource value: 0x7F030077
			public const int chipStyle = 2130903159;
			
			// aapt resource value: 0x7F030078
			public const int closeIcon = 2130903160;
			
			// aapt resource value: 0x7F030079
			public const int closeIconEnabled = 2130903161;
			
			// aapt resource value: 0x7F03007A
			public const int closeIconEndPadding = 2130903162;
			
			// aapt resource value: 0x7F03007B
			public const int closeIconSize = 2130903163;
			
			// aapt resource value: 0x7F03007C
			public const int closeIconStartPadding = 2130903164;
			
			// aapt resource value: 0x7F03007D
			public const int closeIconTint = 2130903165;
			
			// aapt resource value: 0x7F03007E
			public const int closeIconVisible = 2130903166;
			
			// aapt resource value: 0x7F03007F
			public const int closeItemLayout = 2130903167;
			
			// aapt resource value: 0x7F030080
			public const int collapseContentDescription = 2130903168;
			
			// aapt resource value: 0x7F030082
			public const int collapsedTitleGravity = 2130903170;
			
			// aapt resource value: 0x7F030083
			public const int collapsedTitleTextAppearance = 2130903171;
			
			// aapt resource value: 0x7F030081
			public const int collapseIcon = 2130903169;
			
			// aapt resource value: 0x7F030084
			public const int color = 2130903172;
			
			// aapt resource value: 0x7F030085
			public const int colorAccent = 2130903173;
			
			// aapt resource value: 0x7F030086
			public const int colorBackgroundFloating = 2130903174;
			
			// aapt resource value: 0x7F030087
			public const int colorButtonNormal = 2130903175;
			
			// aapt resource value: 0x7F030088
			public const int colorControlActivated = 2130903176;
			
			// aapt resource value: 0x7F030089
			public const int colorControlHighlight = 2130903177;
			
			// aapt resource value: 0x7F03008A
			public const int colorControlNormal = 2130903178;
			
			// aapt resource value: 0x7F03008B
			public const int colorError = 2130903179;
			
			// aapt resource value: 0x7F03008C
			public const int colorPrimary = 2130903180;
			
			// aapt resource value: 0x7F03008D
			public const int colorPrimaryDark = 2130903181;
			
			// aapt resource value: 0x7F03008E
			public const int colorSecondary = 2130903182;
			
			// aapt resource value: 0x7F03008F
			public const int colorSwitchThumbNormal = 2130903183;
			
			// aapt resource value: 0x7F030090
			public const int commitIcon = 2130903184;
			
			// aapt resource value: 0x7F030091
			public const int contentDescription = 2130903185;
			
			// aapt resource value: 0x7F030092
			public const int contentInsetEnd = 2130903186;
			
			// aapt resource value: 0x7F030093
			public const int contentInsetEndWithActions = 2130903187;
			
			// aapt resource value: 0x7F030094
			public const int contentInsetLeft = 2130903188;
			
			// aapt resource value: 0x7F030095
			public const int contentInsetRight = 2130903189;
			
			// aapt resource value: 0x7F030096
			public const int contentInsetStart = 2130903190;
			
			// aapt resource value: 0x7F030097
			public const int contentInsetStartWithNavigation = 2130903191;
			
			// aapt resource value: 0x7F030098
			public const int contentPadding = 2130903192;
			
			// aapt resource value: 0x7F030099
			public const int contentPaddingBottom = 2130903193;
			
			// aapt resource value: 0x7F03009A
			public const int contentPaddingLeft = 2130903194;
			
			// aapt resource value: 0x7F03009B
			public const int contentPaddingRight = 2130903195;
			
			// aapt resource value: 0x7F03009C
			public const int contentPaddingTop = 2130903196;
			
			// aapt resource value: 0x7F03009D
			public const int contentScrim = 2130903197;
			
			// aapt resource value: 0x7F03009E
			public const int controlBackground = 2130903198;
			
			// aapt resource value: 0x7F03009F
			public const int coordinatorLayoutStyle = 2130903199;
			
			// aapt resource value: 0x7F0300A0
			public const int cornerRadius = 2130903200;
			
			// aapt resource value: 0x7F0300A1
			public const int counterEnabled = 2130903201;
			
			// aapt resource value: 0x7F0300A2
			public const int counterMaxLength = 2130903202;
			
			// aapt resource value: 0x7F0300A3
			public const int counterOverflowTextAppearance = 2130903203;
			
			// aapt resource value: 0x7F0300A4
			public const int counterTextAppearance = 2130903204;
			
			// aapt resource value: 0x7F0300A5
			public const int customNavigationLayout = 2130903205;
			
			// aapt resource value: 0x7F0300A6
			public const int defaultQueryHint = 2130903206;
			
			// aapt resource value: 0x7F0300A7
			public const int dialogCornerRadius = 2130903207;
			
			// aapt resource value: 0x7F0300A8
			public const int dialogPreferredPadding = 2130903208;
			
			// aapt resource value: 0x7F0300A9
			public const int dialogTheme = 2130903209;
			
			// aapt resource value: 0x7F0300AA
			public const int displayOptions = 2130903210;
			
			// aapt resource value: 0x7F0300AB
			public const int divider = 2130903211;
			
			// aapt resource value: 0x7F0300AC
			public const int dividerHorizontal = 2130903212;
			
			// aapt resource value: 0x7F0300AD
			public const int dividerPadding = 2130903213;
			
			// aapt resource value: 0x7F0300AE
			public const int dividerVertical = 2130903214;
			
			// aapt resource value: 0x7F0300AF
			public const int drawableBottomCompat = 2130903215;
			
			// aapt resource value: 0x7F0300B0
			public const int drawableEndCompat = 2130903216;
			
			// aapt resource value: 0x7F0300B1
			public const int drawableLeftCompat = 2130903217;
			
			// aapt resource value: 0x7F0300B2
			public const int drawableRightCompat = 2130903218;
			
			// aapt resource value: 0x7F0300B3
			public const int drawableSize = 2130903219;
			
			// aapt resource value: 0x7F0300B4
			public const int drawableStartCompat = 2130903220;
			
			// aapt resource value: 0x7F0300B5
			public const int drawableTint = 2130903221;
			
			// aapt resource value: 0x7F0300B6
			public const int drawableTintMode = 2130903222;
			
			// aapt resource value: 0x7F0300B7
			public const int drawableTopCompat = 2130903223;
			
			// aapt resource value: 0x7F0300B8
			public const int drawerArrowStyle = 2130903224;
			
			// aapt resource value: 0x7F0300B9
			public const int drawerLayoutStyle = 2130903225;
			
			// aapt resource value: 0x7F0300BB
			public const int dropdownListPreferredItemHeight = 2130903227;
			
			// aapt resource value: 0x7F0300BA
			public const int dropDownListViewStyle = 2130903226;
			
			// aapt resource value: 0x7F0300BC
			public const int editTextBackground = 2130903228;
			
			// aapt resource value: 0x7F0300BD
			public const int editTextColor = 2130903229;
			
			// aapt resource value: 0x7F0300BE
			public const int editTextStyle = 2130903230;
			
			// aapt resource value: 0x7F0300BF
			public const int elevation = 2130903231;
			
			// aapt resource value: 0x7F0300C0
			public const int enforceMaterialTheme = 2130903232;
			
			// aapt resource value: 0x7F0300C1
			public const int enforceTextAppearance = 2130903233;
			
			// aapt resource value: 0x7F0300C2
			public const int errorEnabled = 2130903234;
			
			// aapt resource value: 0x7F0300C3
			public const int errorTextAppearance = 2130903235;
			
			// aapt resource value: 0x7F0300C4
			public const int expandActivityOverflowButtonDrawable = 2130903236;
			
			// aapt resource value: 0x7F0300C5
			public const int expanded = 2130903237;
			
			// aapt resource value: 0x7F0300C6
			public const int expandedTitleGravity = 2130903238;
			
			// aapt resource value: 0x7F0300C7
			public const int expandedTitleMargin = 2130903239;
			
			// aapt resource value: 0x7F0300C8
			public const int expandedTitleMarginBottom = 2130903240;
			
			// aapt resource value: 0x7F0300C9
			public const int expandedTitleMarginEnd = 2130903241;
			
			// aapt resource value: 0x7F0300CA
			public const int expandedTitleMarginStart = 2130903242;
			
			// aapt resource value: 0x7F0300CB
			public const int expandedTitleMarginTop = 2130903243;
			
			// aapt resource value: 0x7F0300CC
			public const int expandedTitleTextAppearance = 2130903244;
			
			// aapt resource value: 0x7F0300CD
			public const int fabAlignmentMode = 2130903245;
			
			// aapt resource value: 0x7F0300CE
			public const int fabCradleMargin = 2130903246;
			
			// aapt resource value: 0x7F0300CF
			public const int fabCradleRoundedCornerRadius = 2130903247;
			
			// aapt resource value: 0x7F0300D0
			public const int fabCradleVerticalOffset = 2130903248;
			
			// aapt resource value: 0x7F0300D1
			public const int fabCustomSize = 2130903249;
			
			// aapt resource value: 0x7F0300D2
			public const int fabSize = 2130903250;
			
			// aapt resource value: 0x7F0300D3
			public const int fastScrollEnabled = 2130903251;
			
			// aapt resource value: 0x7F0300D4
			public const int fastScrollHorizontalThumbDrawable = 2130903252;
			
			// aapt resource value: 0x7F0300D5
			public const int fastScrollHorizontalTrackDrawable = 2130903253;
			
			// aapt resource value: 0x7F0300D6
			public const int fastScrollVerticalThumbDrawable = 2130903254;
			
			// aapt resource value: 0x7F0300D7
			public const int fastScrollVerticalTrackDrawable = 2130903255;
			
			// aapt resource value: 0x7F0300D8
			public const int firstBaselineToTopHeight = 2130903256;
			
			// aapt resource value: 0x7F0300D9
			public const int floatingActionButtonStyle = 2130903257;
			
			// aapt resource value: 0x7F0300DA
			public const int font = 2130903258;
			
			// aapt resource value: 0x7F0300DB
			public const int fontFamily = 2130903259;
			
			// aapt resource value: 0x7F0300DC
			public const int fontProviderAuthority = 2130903260;
			
			// aapt resource value: 0x7F0300DD
			public const int fontProviderCerts = 2130903261;
			
			// aapt resource value: 0x7F0300DE
			public const int fontProviderFetchStrategy = 2130903262;
			
			// aapt resource value: 0x7F0300DF
			public const int fontProviderFetchTimeout = 2130903263;
			
			// aapt resource value: 0x7F0300E0
			public const int fontProviderPackage = 2130903264;
			
			// aapt resource value: 0x7F0300E1
			public const int fontProviderQuery = 2130903265;
			
			// aapt resource value: 0x7F0300E2
			public const int fontStyle = 2130903266;
			
			// aapt resource value: 0x7F0300E3
			public const int fontVariationSettings = 2130903267;
			
			// aapt resource value: 0x7F0300E4
			public const int fontWeight = 2130903268;
			
			// aapt resource value: 0x7F0300E5
			public const int foregroundInsidePadding = 2130903269;
			
			// aapt resource value: 0x7F0300E6
			public const int gapBetweenBars = 2130903270;
			
			// aapt resource value: 0x7F0300E7
			public const int goIcon = 2130903271;
			
			// aapt resource value: 0x7F0300E8
			public const int headerLayout = 2130903272;
			
			// aapt resource value: 0x7F0300E9
			public const int height = 2130903273;
			
			// aapt resource value: 0x7F0300EA
			public const int helperText = 2130903274;
			
			// aapt resource value: 0x7F0300EB
			public const int helperTextEnabled = 2130903275;
			
			// aapt resource value: 0x7F0300EC
			public const int helperTextTextAppearance = 2130903276;
			
			// aapt resource value: 0x7F0300ED
			public const int hideMotionSpec = 2130903277;
			
			// aapt resource value: 0x7F0300EE
			public const int hideOnContentScroll = 2130903278;
			
			// aapt resource value: 0x7F0300EF
			public const int hideOnScroll = 2130903279;
			
			// aapt resource value: 0x7F0300F0
			public const int hintAnimationEnabled = 2130903280;
			
			// aapt resource value: 0x7F0300F1
			public const int hintEnabled = 2130903281;
			
			// aapt resource value: 0x7F0300F2
			public const int hintTextAppearance = 2130903282;
			
			// aapt resource value: 0x7F0300F3
			public const int homeAsUpIndicator = 2130903283;
			
			// aapt resource value: 0x7F0300F4
			public const int homeLayout = 2130903284;
			
			// aapt resource value: 0x7F0300F5
			public const int hoveredFocusedTranslationZ = 2130903285;
			
			// aapt resource value: 0x7F0300F6
			public const int icon = 2130903286;
			
			// aapt resource value: 0x7F0300F7
			public const int iconEndPadding = 2130903287;
			
			// aapt resource value: 0x7F0300F8
			public const int iconGravity = 2130903288;
			
			// aapt resource value: 0x7F0300FE
			public const int iconifiedByDefault = 2130903294;
			
			// aapt resource value: 0x7F0300F9
			public const int iconPadding = 2130903289;
			
			// aapt resource value: 0x7F0300FA
			public const int iconSize = 2130903290;
			
			// aapt resource value: 0x7F0300FB
			public const int iconStartPadding = 2130903291;
			
			// aapt resource value: 0x7F0300FC
			public const int iconTint = 2130903292;
			
			// aapt resource value: 0x7F0300FD
			public const int iconTintMode = 2130903293;
			
			// aapt resource value: 0x7F0300FF
			public const int imageButtonStyle = 2130903295;
			
			// aapt resource value: 0x7F030100
			public const int indeterminateProgressStyle = 2130903296;
			
			// aapt resource value: 0x7F030101
			public const int initialActivityCount = 2130903297;
			
			// aapt resource value: 0x7F030102
			public const int insetForeground = 2130903298;
			
			// aapt resource value: 0x7F030103
			public const int isLightTheme = 2130903299;
			
			// aapt resource value: 0x7F030104
			public const int itemBackground = 2130903300;
			
			// aapt resource value: 0x7F030105
			public const int itemHorizontalPadding = 2130903301;
			
			// aapt resource value: 0x7F030106
			public const int itemHorizontalTranslationEnabled = 2130903302;
			
			// aapt resource value: 0x7F030107
			public const int itemIconPadding = 2130903303;
			
			// aapt resource value: 0x7F030108
			public const int itemIconSize = 2130903304;
			
			// aapt resource value: 0x7F030109
			public const int itemIconTint = 2130903305;
			
			// aapt resource value: 0x7F03010A
			public const int itemPadding = 2130903306;
			
			// aapt resource value: 0x7F03010B
			public const int itemSpacing = 2130903307;
			
			// aapt resource value: 0x7F03010C
			public const int itemTextAppearance = 2130903308;
			
			// aapt resource value: 0x7F03010D
			public const int itemTextAppearanceActive = 2130903309;
			
			// aapt resource value: 0x7F03010E
			public const int itemTextAppearanceInactive = 2130903310;
			
			// aapt resource value: 0x7F03010F
			public const int itemTextColor = 2130903311;
			
			// aapt resource value: 0x7F030110
			public const int keylines = 2130903312;
			
			// aapt resource value: 0x7F030111
			public const int labelVisibilityMode = 2130903313;
			
			// aapt resource value: 0x7F030112
			public const int lastBaselineToBottomHeight = 2130903314;
			
			// aapt resource value: 0x7F030113
			public const int layout = 2130903315;
			
			// aapt resource value: 0x7F030114
			public const int layoutManager = 2130903316;
			
			// aapt resource value: 0x7F030115
			public const int layout_anchor = 2130903317;
			
			// aapt resource value: 0x7F030116
			public const int layout_anchorGravity = 2130903318;
			
			// aapt resource value: 0x7F030117
			public const int layout_behavior = 2130903319;
			
			// aapt resource value: 0x7F030118
			public const int layout_collapseMode = 2130903320;
			
			// aapt resource value: 0x7F030119
			public const int layout_collapseParallaxMultiplier = 2130903321;
			
			// aapt resource value: 0x7F03011A
			public const int layout_dodgeInsetEdges = 2130903322;
			
			// aapt resource value: 0x7F03011B
			public const int layout_insetEdge = 2130903323;
			
			// aapt resource value: 0x7F03011C
			public const int layout_keyline = 2130903324;
			
			// aapt resource value: 0x7F03011D
			public const int layout_scrollFlags = 2130903325;
			
			// aapt resource value: 0x7F03011E
			public const int layout_scrollInterpolator = 2130903326;
			
			// aapt resource value: 0x7F03011F
			public const int liftOnScroll = 2130903327;
			
			// aapt resource value: 0x7F030120
			public const int lineHeight = 2130903328;
			
			// aapt resource value: 0x7F030121
			public const int lineSpacing = 2130903329;
			
			// aapt resource value: 0x7F030122
			public const int listChoiceBackgroundIndicator = 2130903330;
			
			// aapt resource value: 0x7F030123
			public const int listChoiceIndicatorMultipleAnimated = 2130903331;
			
			// aapt resource value: 0x7F030124
			public const int listChoiceIndicatorSingleAnimated = 2130903332;
			
			// aapt resource value: 0x7F030125
			public const int listDividerAlertDialog = 2130903333;
			
			// aapt resource value: 0x7F030126
			public const int listItemLayout = 2130903334;
			
			// aapt resource value: 0x7F030127
			public const int listLayout = 2130903335;
			
			// aapt resource value: 0x7F030128
			public const int listMenuViewStyle = 2130903336;
			
			// aapt resource value: 0x7F030129
			public const int listPopupWindowStyle = 2130903337;
			
			// aapt resource value: 0x7F03012A
			public const int listPreferredItemHeight = 2130903338;
			
			// aapt resource value: 0x7F03012B
			public const int listPreferredItemHeightLarge = 2130903339;
			
			// aapt resource value: 0x7F03012C
			public const int listPreferredItemHeightSmall = 2130903340;
			
			// aapt resource value: 0x7F03012D
			public const int listPreferredItemPaddingEnd = 2130903341;
			
			// aapt resource value: 0x7F03012E
			public const int listPreferredItemPaddingLeft = 2130903342;
			
			// aapt resource value: 0x7F03012F
			public const int listPreferredItemPaddingRight = 2130903343;
			
			// aapt resource value: 0x7F030130
			public const int listPreferredItemPaddingStart = 2130903344;
			
			// aapt resource value: 0x7F030131
			public const int logo = 2130903345;
			
			// aapt resource value: 0x7F030132
			public const int logoDescription = 2130903346;
			
			// aapt resource value: 0x7F030133
			public const int materialButtonStyle = 2130903347;
			
			// aapt resource value: 0x7F030134
			public const int materialCardViewStyle = 2130903348;
			
			// aapt resource value: 0x7F030135
			public const int maxActionInlineWidth = 2130903349;
			
			// aapt resource value: 0x7F030136
			public const int maxButtonHeight = 2130903350;
			
			// aapt resource value: 0x7F030137
			public const int maxImageSize = 2130903351;
			
			// aapt resource value: 0x7F030138
			public const int measureWithLargestChild = 2130903352;
			
			// aapt resource value: 0x7F030139
			public const int menu = 2130903353;
			
			// aapt resource value: 0x7F03013A
			public const int multiChoiceItemLayout = 2130903354;
			
			// aapt resource value: 0x7F03013B
			public const int navigationContentDescription = 2130903355;
			
			// aapt resource value: 0x7F03013C
			public const int navigationIcon = 2130903356;
			
			// aapt resource value: 0x7F03013D
			public const int navigationMode = 2130903357;
			
			// aapt resource value: 0x7F03013E
			public const int navigationViewStyle = 2130903358;
			
			// aapt resource value: 0x7F03013F
			public const int numericModifiers = 2130903359;
			
			// aapt resource value: 0x7F030140
			public const int overlapAnchor = 2130903360;
			
			// aapt resource value: 0x7F030141
			public const int paddingBottomNoButtons = 2130903361;
			
			// aapt resource value: 0x7F030142
			public const int paddingEnd = 2130903362;
			
			// aapt resource value: 0x7F030143
			public const int paddingStart = 2130903363;
			
			// aapt resource value: 0x7F030144
			public const int paddingTopNoTitle = 2130903364;
			
			// aapt resource value: 0x7F030145
			public const int panelBackground = 2130903365;
			
			// aapt resource value: 0x7F030146
			public const int panelMenuListTheme = 2130903366;
			
			// aapt resource value: 0x7F030147
			public const int panelMenuListWidth = 2130903367;
			
			// aapt resource value: 0x7F030148
			public const int passwordToggleContentDescription = 2130903368;
			
			// aapt resource value: 0x7F030149
			public const int passwordToggleDrawable = 2130903369;
			
			// aapt resource value: 0x7F03014A
			public const int passwordToggleEnabled = 2130903370;
			
			// aapt resource value: 0x7F03014B
			public const int passwordToggleTint = 2130903371;
			
			// aapt resource value: 0x7F03014C
			public const int passwordToggleTintMode = 2130903372;
			
			// aapt resource value: 0x7F03014D
			public const int popupMenuStyle = 2130903373;
			
			// aapt resource value: 0x7F03014E
			public const int popupTheme = 2130903374;
			
			// aapt resource value: 0x7F03014F
			public const int popupWindowStyle = 2130903375;
			
			// aapt resource value: 0x7F030150
			public const int preserveIconSpacing = 2130903376;
			
			// aapt resource value: 0x7F030151
			public const int pressedTranslationZ = 2130903377;
			
			// aapt resource value: 0x7F030152
			public const int progressBarPadding = 2130903378;
			
			// aapt resource value: 0x7F030153
			public const int progressBarStyle = 2130903379;
			
			// aapt resource value: 0x7F030154
			public const int queryBackground = 2130903380;
			
			// aapt resource value: 0x7F030155
			public const int queryHint = 2130903381;
			
			// aapt resource value: 0x7F030156
			public const int radioButtonStyle = 2130903382;
			
			// aapt resource value: 0x7F030157
			public const int ratingBarStyle = 2130903383;
			
			// aapt resource value: 0x7F030158
			public const int ratingBarStyleIndicator = 2130903384;
			
			// aapt resource value: 0x7F030159
			public const int ratingBarStyleSmall = 2130903385;
			
			// aapt resource value: 0x7F03015A
			public const int recyclerViewStyle = 2130903386;
			
			// aapt resource value: 0x7F03015B
			public const int reverseLayout = 2130903387;
			
			// aapt resource value: 0x7F03015C
			public const int rippleColor = 2130903388;
			
			// aapt resource value: 0x7F03015D
			public const int scrimAnimationDuration = 2130903389;
			
			// aapt resource value: 0x7F03015E
			public const int scrimBackground = 2130903390;
			
			// aapt resource value: 0x7F03015F
			public const int scrimVisibleHeightTrigger = 2130903391;
			
			// aapt resource value: 0x7F030160
			public const int searchHintIcon = 2130903392;
			
			// aapt resource value: 0x7F030161
			public const int searchIcon = 2130903393;
			
			// aapt resource value: 0x7F030162
			public const int searchViewStyle = 2130903394;
			
			// aapt resource value: 0x7F030163
			public const int seekBarStyle = 2130903395;
			
			// aapt resource value: 0x7F030164
			public const int selectableItemBackground = 2130903396;
			
			// aapt resource value: 0x7F030165
			public const int selectableItemBackgroundBorderless = 2130903397;
			
			// aapt resource value: 0x7F030166
			public const int showAsAction = 2130903398;
			
			// aapt resource value: 0x7F030167
			public const int showDividers = 2130903399;
			
			// aapt resource value: 0x7F030168
			public const int showMotionSpec = 2130903400;
			
			// aapt resource value: 0x7F030169
			public const int showText = 2130903401;
			
			// aapt resource value: 0x7F03016A
			public const int showTitle = 2130903402;
			
			// aapt resource value: 0x7F03016B
			public const int singleChoiceItemLayout = 2130903403;
			
			// aapt resource value: 0x7F03016C
			public const int singleLine = 2130903404;
			
			// aapt resource value: 0x7F03016D
			public const int singleSelection = 2130903405;
			
			// aapt resource value: 0x7F03016E
			public const int snackbarButtonStyle = 2130903406;
			
			// aapt resource value: 0x7F03016F
			public const int snackbarStyle = 2130903407;
			
			// aapt resource value: 0x7F030170
			public const int spanCount = 2130903408;
			
			// aapt resource value: 0x7F030171
			public const int spinBars = 2130903409;
			
			// aapt resource value: 0x7F030172
			public const int spinnerDropDownItemStyle = 2130903410;
			
			// aapt resource value: 0x7F030173
			public const int spinnerStyle = 2130903411;
			
			// aapt resource value: 0x7F030174
			public const int splitTrack = 2130903412;
			
			// aapt resource value: 0x7F030175
			public const int srcCompat = 2130903413;
			
			// aapt resource value: 0x7F030176
			public const int stackFromEnd = 2130903414;
			
			// aapt resource value: 0x7F030177
			public const int state_above_anchor = 2130903415;
			
			// aapt resource value: 0x7F030178
			public const int state_collapsed = 2130903416;
			
			// aapt resource value: 0x7F030179
			public const int state_collapsible = 2130903417;
			
			// aapt resource value: 0x7F03017A
			public const int state_liftable = 2130903418;
			
			// aapt resource value: 0x7F03017B
			public const int state_lifted = 2130903419;
			
			// aapt resource value: 0x7F03017C
			public const int statusBarBackground = 2130903420;
			
			// aapt resource value: 0x7F03017D
			public const int statusBarScrim = 2130903421;
			
			// aapt resource value: 0x7F03017E
			public const int strokeColor = 2130903422;
			
			// aapt resource value: 0x7F03017F
			public const int strokeWidth = 2130903423;
			
			// aapt resource value: 0x7F030180
			public const int subMenuArrow = 2130903424;
			
			// aapt resource value: 0x7F030181
			public const int submitBackground = 2130903425;
			
			// aapt resource value: 0x7F030182
			public const int subtitle = 2130903426;
			
			// aapt resource value: 0x7F030183
			public const int subtitleTextAppearance = 2130903427;
			
			// aapt resource value: 0x7F030184
			public const int subtitleTextColor = 2130903428;
			
			// aapt resource value: 0x7F030185
			public const int subtitleTextStyle = 2130903429;
			
			// aapt resource value: 0x7F030186
			public const int suggestionRowLayout = 2130903430;
			
			// aapt resource value: 0x7F030187
			public const int switchMinWidth = 2130903431;
			
			// aapt resource value: 0x7F030188
			public const int switchPadding = 2130903432;
			
			// aapt resource value: 0x7F030189
			public const int switchStyle = 2130903433;
			
			// aapt resource value: 0x7F03018A
			public const int switchTextAppearance = 2130903434;
			
			// aapt resource value: 0x7F03018B
			public const int tabBackground = 2130903435;
			
			// aapt resource value: 0x7F03018C
			public const int tabContentStart = 2130903436;
			
			// aapt resource value: 0x7F03018D
			public const int tabGravity = 2130903437;
			
			// aapt resource value: 0x7F03018E
			public const int tabIconTint = 2130903438;
			
			// aapt resource value: 0x7F03018F
			public const int tabIconTintMode = 2130903439;
			
			// aapt resource value: 0x7F030190
			public const int tabIndicator = 2130903440;
			
			// aapt resource value: 0x7F030191
			public const int tabIndicatorAnimationDuration = 2130903441;
			
			// aapt resource value: 0x7F030192
			public const int tabIndicatorColor = 2130903442;
			
			// aapt resource value: 0x7F030193
			public const int tabIndicatorFullWidth = 2130903443;
			
			// aapt resource value: 0x7F030194
			public const int tabIndicatorGravity = 2130903444;
			
			// aapt resource value: 0x7F030195
			public const int tabIndicatorHeight = 2130903445;
			
			// aapt resource value: 0x7F030196
			public const int tabInlineLabel = 2130903446;
			
			// aapt resource value: 0x7F030197
			public const int tabMaxWidth = 2130903447;
			
			// aapt resource value: 0x7F030198
			public const int tabMinWidth = 2130903448;
			
			// aapt resource value: 0x7F030199
			public const int tabMode = 2130903449;
			
			// aapt resource value: 0x7F03019A
			public const int tabPadding = 2130903450;
			
			// aapt resource value: 0x7F03019B
			public const int tabPaddingBottom = 2130903451;
			
			// aapt resource value: 0x7F03019C
			public const int tabPaddingEnd = 2130903452;
			
			// aapt resource value: 0x7F03019D
			public const int tabPaddingStart = 2130903453;
			
			// aapt resource value: 0x7F03019E
			public const int tabPaddingTop = 2130903454;
			
			// aapt resource value: 0x7F03019F
			public const int tabRippleColor = 2130903455;
			
			// aapt resource value: 0x7F0301A0
			public const int tabSelectedTextColor = 2130903456;
			
			// aapt resource value: 0x7F0301A1
			public const int tabStyle = 2130903457;
			
			// aapt resource value: 0x7F0301A2
			public const int tabTextAppearance = 2130903458;
			
			// aapt resource value: 0x7F0301A3
			public const int tabTextColor = 2130903459;
			
			// aapt resource value: 0x7F0301A4
			public const int tabUnboundedRipple = 2130903460;
			
			// aapt resource value: 0x7F0301A5
			public const int textAllCaps = 2130903461;
			
			// aapt resource value: 0x7F0301A6
			public const int textAppearanceBody1 = 2130903462;
			
			// aapt resource value: 0x7F0301A7
			public const int textAppearanceBody2 = 2130903463;
			
			// aapt resource value: 0x7F0301A8
			public const int textAppearanceButton = 2130903464;
			
			// aapt resource value: 0x7F0301A9
			public const int textAppearanceCaption = 2130903465;
			
			// aapt resource value: 0x7F0301AA
			public const int textAppearanceHeadline1 = 2130903466;
			
			// aapt resource value: 0x7F0301AB
			public const int textAppearanceHeadline2 = 2130903467;
			
			// aapt resource value: 0x7F0301AC
			public const int textAppearanceHeadline3 = 2130903468;
			
			// aapt resource value: 0x7F0301AD
			public const int textAppearanceHeadline4 = 2130903469;
			
			// aapt resource value: 0x7F0301AE
			public const int textAppearanceHeadline5 = 2130903470;
			
			// aapt resource value: 0x7F0301AF
			public const int textAppearanceHeadline6 = 2130903471;
			
			// aapt resource value: 0x7F0301B0
			public const int textAppearanceLargePopupMenu = 2130903472;
			
			// aapt resource value: 0x7F0301B1
			public const int textAppearanceListItem = 2130903473;
			
			// aapt resource value: 0x7F0301B2
			public const int textAppearanceListItemSecondary = 2130903474;
			
			// aapt resource value: 0x7F0301B3
			public const int textAppearanceListItemSmall = 2130903475;
			
			// aapt resource value: 0x7F0301B4
			public const int textAppearanceOverline = 2130903476;
			
			// aapt resource value: 0x7F0301B5
			public const int textAppearancePopupMenuHeader = 2130903477;
			
			// aapt resource value: 0x7F0301B6
			public const int textAppearanceSearchResultSubtitle = 2130903478;
			
			// aapt resource value: 0x7F0301B7
			public const int textAppearanceSearchResultTitle = 2130903479;
			
			// aapt resource value: 0x7F0301B8
			public const int textAppearanceSmallPopupMenu = 2130903480;
			
			// aapt resource value: 0x7F0301B9
			public const int textAppearanceSubtitle1 = 2130903481;
			
			// aapt resource value: 0x7F0301BA
			public const int textAppearanceSubtitle2 = 2130903482;
			
			// aapt resource value: 0x7F0301BB
			public const int textColorAlertDialogListItem = 2130903483;
			
			// aapt resource value: 0x7F0301BC
			public const int textColorSearchUrl = 2130903484;
			
			// aapt resource value: 0x7F0301BD
			public const int textEndPadding = 2130903485;
			
			// aapt resource value: 0x7F0301BE
			public const int textInputStyle = 2130903486;
			
			// aapt resource value: 0x7F0301BF
			public const int textLocale = 2130903487;
			
			// aapt resource value: 0x7F0301C0
			public const int textStartPadding = 2130903488;
			
			// aapt resource value: 0x7F0301C1
			public const int theme = 2130903489;
			
			// aapt resource value: 0x7F0301C2
			public const int thickness = 2130903490;
			
			// aapt resource value: 0x7F0301C3
			public const int thumbTextPadding = 2130903491;
			
			// aapt resource value: 0x7F0301C4
			public const int thumbTint = 2130903492;
			
			// aapt resource value: 0x7F0301C5
			public const int thumbTintMode = 2130903493;
			
			// aapt resource value: 0x7F0301C6
			public const int tickMark = 2130903494;
			
			// aapt resource value: 0x7F0301C7
			public const int tickMarkTint = 2130903495;
			
			// aapt resource value: 0x7F0301C8
			public const int tickMarkTintMode = 2130903496;
			
			// aapt resource value: 0x7F0301C9
			public const int tint = 2130903497;
			
			// aapt resource value: 0x7F0301CA
			public const int tintMode = 2130903498;
			
			// aapt resource value: 0x7F0301CB
			public const int title = 2130903499;
			
			// aapt resource value: 0x7F0301CC
			public const int titleEnabled = 2130903500;
			
			// aapt resource value: 0x7F0301CD
			public const int titleMargin = 2130903501;
			
			// aapt resource value: 0x7F0301CE
			public const int titleMarginBottom = 2130903502;
			
			// aapt resource value: 0x7F0301CF
			public const int titleMarginEnd = 2130903503;
			
			// aapt resource value: 0x7F0301D2
			public const int titleMargins = 2130903506;
			
			// aapt resource value: 0x7F0301D0
			public const int titleMarginStart = 2130903504;
			
			// aapt resource value: 0x7F0301D1
			public const int titleMarginTop = 2130903505;
			
			// aapt resource value: 0x7F0301D3
			public const int titleTextAppearance = 2130903507;
			
			// aapt resource value: 0x7F0301D4
			public const int titleTextColor = 2130903508;
			
			// aapt resource value: 0x7F0301D5
			public const int titleTextStyle = 2130903509;
			
			// aapt resource value: 0x7F0301D6
			public const int toolbarId = 2130903510;
			
			// aapt resource value: 0x7F0301D7
			public const int toolbarNavigationButtonStyle = 2130903511;
			
			// aapt resource value: 0x7F0301D8
			public const int toolbarStyle = 2130903512;
			
			// aapt resource value: 0x7F0301D9
			public const int tooltipForegroundColor = 2130903513;
			
			// aapt resource value: 0x7F0301DA
			public const int tooltipFrameBackground = 2130903514;
			
			// aapt resource value: 0x7F0301DB
			public const int tooltipText = 2130903515;
			
			// aapt resource value: 0x7F0301DC
			public const int track = 2130903516;
			
			// aapt resource value: 0x7F0301DD
			public const int trackTint = 2130903517;
			
			// aapt resource value: 0x7F0301DE
			public const int trackTintMode = 2130903518;
			
			// aapt resource value: 0x7F0301DF
			public const int ttcIndex = 2130903519;
			
			// aapt resource value: 0x7F0301E0
			public const int useCompatPadding = 2130903520;
			
			// aapt resource value: 0x7F0301E1
			public const int viewInflaterClass = 2130903521;
			
			// aapt resource value: 0x7F0301E2
			public const int voiceIcon = 2130903522;
			
			// aapt resource value: 0x7F0301E3
			public const int windowActionBar = 2130903523;
			
			// aapt resource value: 0x7F0301E4
			public const int windowActionBarOverlay = 2130903524;
			
			// aapt resource value: 0x7F0301E5
			public const int windowActionModeOverlay = 2130903525;
			
			// aapt resource value: 0x7F0301E6
			public const int windowFixedHeightMajor = 2130903526;
			
			// aapt resource value: 0x7F0301E7
			public const int windowFixedHeightMinor = 2130903527;
			
			// aapt resource value: 0x7F0301E8
			public const int windowFixedWidthMajor = 2130903528;
			
			// aapt resource value: 0x7F0301E9
			public const int windowFixedWidthMinor = 2130903529;
			
			// aapt resource value: 0x7F0301EA
			public const int windowMinWidthMajor = 2130903530;
			
			// aapt resource value: 0x7F0301EB
			public const int windowMinWidthMinor = 2130903531;
			
			// aapt resource value: 0x7F0301EC
			public const int windowNoTitle = 2130903532;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F040000
			public const int abc_action_bar_embed_tabs = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int abc_allow_stacked_button_bar = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int abc_config_actionMenuItemAllCaps = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int mtrl_btn_textappearance_all_caps = 2130968579;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F090000
			public const int abc_config_activityDefaultDur = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int abc_config_activityShortDur = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int app_bar_elevation_anim_duration = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int bottom_sheet_slide_duration = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int cancel_button_image_alpha = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int config_tooltipAnimTime = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int design_snackbar_text_max_lines = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int design_tab_indicator_anim_duration_ms = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int hide_password_duration = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int mtrl_btn_anim_delay_ms = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int mtrl_btn_anim_duration_ms = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int mtrl_chip_anim_duration = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int mtrl_tab_indicator_anim_duration_ms = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int show_password_duration = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int status_bar_notification_info_maxnum = 2131296270;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7F0A0000
			public const int btn_checkbox_checked_mtrl_animation_interpolator_0 = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int btn_checkbox_checked_mtrl_animation_interpolator_1 = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int btn_checkbox_unchecked_mtrl_animation_interpolator_0 = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int btn_checkbox_unchecked_mtrl_animation_interpolator_1 = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int btn_radio_to_off_mtrl_animation_interpolator_0 = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int btn_radio_to_on_mtrl_animation_interpolator_0 = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int fast_out_slow_in = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int mtrl_fast_out_linear_in = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int mtrl_fast_out_slow_in = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int mtrl_linear = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int mtrl_linear_out_slow_in = 2131361802;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
